#!/usr/bin/env python3
"""Batch 3: Pages 16-24 of operator pages."""
import sys
sys.path.insert(0, '.')
from generate_operator_pages import generate_page

BATCH3 = [
    {
        "slug": "medsenior-rj",
        "title": "MedSênior RJ | Plano de Saúde para Idosos 2026 | Virtua Corretora",
        "meta_description": "Plano MedSênior no Rio de Janeiro. Especialista em planos para idosos 60+. Preços 2026. Cotação grátis com corretor autorizado.",
        "h1": "MedSênior<br>Rio de Janeiro",
        "operator_name": "MedSênior",
        "hero_subtitle": "A MedSênior é uma operadora especializada no público 60+, oferecendo planos de saúde com atendimento geriátrico, rede credenciada selecionada e preços diferenciados para idosos no Rio de Janeiro.",
        "hero_gradient": "linear-gradient(135deg, #2c3e50 0%, #3498db 50%, #2980b9 100%)",
        "hero_text_color": "#2c3e50",
        "accent_color": "#3498db",
        "badges": ["Especialista 60+", "Preços 2026", "Rio de Janeiro", "Geriatria"],
        "whatsapp_msg": "Olá, gostaria de uma cotação do plano MedSênior RJ",
        "benefits_title": "Por que escolher a MedSênior?",
        "benefits_subtitle": "Operadora especializada no cuidado do público 60+ com programas específicos de longevidade.",
        "benefits": [
            {"icon": "👨‍⚕️", "title": "Especialista em Idosos", "desc": "Operadora criada especialmente para atender as necessidades do público 60+."},
            {"icon": "💰", "title": "Preços para 60+", "desc": "Valores diferenciados e competitivos para a faixa etária acima de 60 anos."},
            {"icon": "🏥", "title": "Rede Selecionada", "desc": "Hospitais e clínicas especializados no atendimento ao público idoso."},
            {"icon": "💊", "title": "Programas de Prevenção", "desc": "Acompanhamento geriátrico e programas de saúde preventiva."},
            {"icon": "📱", "title": "Telemedicina", "desc": "Consultas médicas online facilitando o acesso para quem tem dificuldade de locomoção."},
            {"icon": "🌍", "title": "Cobertura RJ", "desc": "Rede credenciada no Rio de Janeiro capital e região metropolitana."},
        ],
        "plans_title": "Planos MedSênior",
        "plans_subtitle": "Opções pensadas especificamente para o público 60+.",
        "plans": [
            {"name": "MedSênior Básico", "type": "Regional RJ · Enfermaria", "items": ["Cobertura no RJ", "Enfermaria", "Consultas geriátricas", "Exames e internações", "Programa preventivo"]},
            {"name": "MedSênior Completo", "type": "Regional RJ · Apartamento", "featured": True, "items": ["Rede ampla no RJ", "Apartamento", "Geriatria + especialidades", "Sem coparticipação", "Acompanhamento contínuo"]},
            {"name": "MedSênior Premium", "type": "Nacional · Apartamento", "items": ["Cobertura nacional", "Rede premium", "Reembolso", "Programas de longevidade", "Assistência completa"]},
        ],
        "network_title": "Rede Credenciada MedSênior RJ",
        "network_subtitle": "Hospitais e clínicas no Rio de Janeiro especializados em atendimento ao idoso.",
        "network": ["Hospitais no RJ", "Clínicas Geriátricas", "Laboratórios credenciados", "Centros de Diagnóstico", "Fisioterapia", "Clínicas de Reabilitação", "Prontos-Socorros", "Maternidades", "Farmácias Parceiras", "Centros de Bem-estar"],
        "faqs": [
            {"q": "A MedSênior é só para idosos?", "a": "Sim, é especializada no público 60+, oferecendo planos focados nas necessidades dessa faixa etária."},
            {"q": "Qual o preço do MedSênior?", "a": "Valores competitivos para 60+. Solicite cotação para preços atualizados."},
            {"q": "Onde a MedSênior atende no RJ?", "a": "Capital e região metropolitana do Rio de Janeiro."},
            {"q": "A MedSênior tem geriatria?", "a": "Sim! Acompanhamento geriátrico é um dos diferenciais da operadora."},
        ],
    },
    {
        "slug": "plano-de-saude-prevent-senior",
        "title": "Prevent Senior | Plano de Saúde 2026 | Virtua Corretora",
        "meta_description": "Plano de Saúde Prevent Senior 2026. Especialista em planos para idosos com rede própria. Individual e empresarial. Cotação grátis.",
        "h1": "Plano de Saúde<br>Prevent Senior",
        "operator_name": "Prevent Senior",
        "hero_subtitle": "A Prevent Senior é especialista em planos de saúde para o público sênior, com rede própria de hospitais e centros médicos. Atendimento diferenciado e preços competitivos para todas as idades.",
        "hero_gradient": "linear-gradient(135deg, #1b4332 0%, #2d6a4f 50%, #40916c 100%)",
        "hero_text_color": "#1b4332",
        "accent_color": "#2d6a4f",
        "badges": ["Corretor Autorizado", "Preços 2026", "Rede Própria", "Especialista Sênior"],
        "whatsapp_msg": "Olá, gostaria de uma cotação do plano Prevent Senior",
        "benefits_title": "Por que escolher a Prevent Senior?",
        "benefits_subtitle": "Rede própria de hospitais e centros médicos com foco na qualidade do atendimento.",
        "benefits": [
            {"icon": "🏥", "title": "Rede Própria", "desc": "Hospitais e centros médicos próprios garantindo controle de qualidade no atendimento."},
            {"icon": "👨‍⚕️", "title": "Foco no Sênior", "desc": "Programas e especialidades voltados ao cuidado do público mais experiente."},
            {"icon": "💰", "title": "Custo Competitivo", "desc": "Planos acessíveis com rede própria, reduzindo custos sem perder qualidade."},
            {"icon": "🔬", "title": "Centros de Diagnóstico", "desc": "Exames em centros próprios com tecnologia de ponta e agilidade."},
            {"icon": "💊", "title": "Programas de Prevenção", "desc": "Medicina preventiva e programas de acompanhamento da saúde."},
            {"icon": "📱", "title": "Atendimento Digital", "desc": "Telemedicina e serviços digitais para facilitar o acesso."},
        ],
        "plans_title": "Planos Prevent Senior",
        "plans_subtitle": "Conheça as opções de planos Prevent Senior.",
        "plans": [
            {"name": "Prevent Básico", "type": "Regional · Enfermaria", "items": ["Rede própria", "Enfermaria", "Consultas e exames", "Programas preventivos", "Pronto-socorro 24h"]},
            {"name": "Prevent Completo", "type": "Regional · Apartamento", "featured": True, "items": ["Rede própria + credenciada", "Apartamento", "Sem coparticipação", "Todas especialidades", "Acompanhamento contínuo"]},
            {"name": "Prevent Premium", "type": "Ampliado · Premium", "items": ["Rede ampliada", "Hospitais referência", "Reembolso opção", "Cobertura ampla", "Benefícios exclusivos"]},
        ],
        "network_title": "Rede Credenciada Prevent Senior",
        "network_subtitle": "Hospitais e centros médicos próprios.",
        "network": ["Hospitais Prevent Senior", "Centros Médicos Prevent", "Centros de Diagnóstico", "Laboratórios próprios", "Prontos-Socorros 24h", "Clínicas de Especialidades", "Centros de Reabilitação", "Programas de Bem-estar"],
        "faqs": [
            {"q": "A Prevent Senior é só para idosos?", "a": "Não! Embora tenha expertise em seniores, oferece planos para todas as idades."},
            {"q": "Onde a Prevent Senior atende?", "a": "Presente em São Paulo e Rio de Janeiro com rede própria."},
            {"q": "A Prevent tem hospital próprio?", "a": "Sim! Hospitais e centros médicos próprios são o grande diferencial."},
            {"q": "Como contratar a Prevent Senior?", "a": "Ligue (22) 99940-4840 ou envie WhatsApp para cotação gratuita."},
        ],
    },
    {
        "slug": "plano-de-saude-hapvida-salvador",
        "title": "Hapvida Salvador | Plano de Saúde BA 2026 | Virtua Corretora",
        "meta_description": "Plano de Saúde Hapvida em Salvador e Bahia. Preços 2026, rede própria. Individual e empresarial. Cotação grátis.",
        "h1": "Plano de Saúde Hapvida<br>Salvador e Bahia",
        "operator_name": "Hapvida Salvador",
        "hero_subtitle": "A Hapvida é a maior operadora da Bahia com ampla rede própria em Salvador, Feira de Santana, Camaçari e todo o estado. Planos acessíveis com cobertura completa.",
        "hero_gradient": "linear-gradient(135deg, #004d00 0%, #006600 50%, #008800 100%)",
        "hero_text_color": "#004d00",
        "accent_color": "#008800",
        "badges": ["Corretor Autorizado", "Preços 2026", "Salvador e BA", "Rede Própria"],
        "whatsapp_msg": "Olá, gostaria de uma cotação do plano Hapvida em Salvador",
        "benefits_title": "Hapvida em Salvador e Bahia",
        "benefits_subtitle": "A maior rede própria de saúde da Bahia.",
        "benefits": [
            {"icon": "🏥", "title": "Rede Própria BA", "desc": "Hospitais, UPAs e laboratórios próprios em Salvador e todo o estado."},
            {"icon": "💰", "title": "Melhor Preço BA", "desc": "Planos com valores acessíveis para o mercado baiano."},
            {"icon": "📱", "title": "Teleconsulta", "desc": "Consultas online pelo app Hapvida."},
            {"icon": "🔬", "title": "Laboratórios Próprios", "desc": "Exames com rapidez na rede de labs Hapvida."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Planos para empresas baianas a partir de 2 vidas."},
            {"icon": "🌍", "title": "Cobertura Estadual", "desc": "Salvador, Feira de Santana, Camaçari, Lauro de Freitas e mais."},
        ],
        "plans_title": "Planos Hapvida em Salvador",
        "plans_subtitle": "Opções para pessoa física e empresas na Bahia.",
        "plans": [
            {"name": "Hapvida Mix BA", "type": "Regional · Enfermaria", "items": ["Rede própria + credenciada na BA", "Coparticipação parcial", "Teleconsulta", "Programa de prevenção", "Enfermaria"]},
            {"name": "Hapvida Pleno BA", "type": "Regional · Apartamento", "featured": True, "items": ["Rede própria completa na BA", "Sem coparticipação rede própria", "Apartamento", "UPAs 24h", "Exames e internações"]},
            {"name": "Hapvida Nacional", "type": "Nacional · Apartamento", "items": ["Cobertura em todo Brasil", "Rede nacional", "Apartamento", "Teleconsulta especialidades", "Medicina preventiva"]},
        ],
        "network_title": "Rede em Salvador e Bahia",
        "network_subtitle": "Hospitais e clínicas próprias Hapvida na Bahia.",
        "network": ["Hospital Hapvida Salvador", "UPAs Hapvida BA", "Hospital em Feira de Santana", "Laboratórios Hapvida", "Centros de Diagnóstico", "Clínicas em Camaçari", "Prontos-Socorros 24h", "Maternidades", "Rede em Lauro de Freitas"],
        "faqs": [
            {"q": "Onde a Hapvida atende na Bahia?", "a": "Salvador, Feira de Santana, Camaçari, Lauro de Freitas, Vitória da Conquista e mais cidades."},
            {"q": "A Hapvida tem hospital em Salvador?", "a": "Sim! Hospitais próprios, UPAs e laboratórios em Salvador."},
            {"q": "Qual o plano mais barato em Salvador?", "a": "O Hapvida Mix BA é a opção mais acessível. Solicite cotação para valores."},
            {"q": "Hapvida Salvador aceita MEI?", "a": "Sim, empresas MEI a partir de 2 vidas."},
        ],
    },
    {
        "slug": "bradesco-seguro-de-vida",
        "title": "Bradesco Seguro de Vida | Preços 2026 | Virtua Corretora",
        "meta_description": "Seguro de Vida Bradesco com preços 2026. Individual e empresarial. Coberturas flexíveis. Cotação grátis com corretor autorizado.",
        "h1": "Bradesco<br>Seguro de Vida",
        "operator_name": "Bradesco Seguros",
        "hero_subtitle": "O Seguro de Vida Bradesco oferece proteção financeira para você e sua família com coberturas flexíveis, assistências completas e a solidez da maior seguradora do Brasil.",
        "hero_gradient": "linear-gradient(135deg, #8B0000 0%, #CC0000 50%, #FF1A1A 100%)",
        "hero_text_color": "#8B0000",
        "accent_color": "#CC0000",
        "badges": ["Corretor Autorizado", "Preços 2026", "Maior Seguradora do Brasil", "Coberturas Flexíveis"],
        "whatsapp_msg": "Olá, gostaria de uma cotação de seguro de vida Bradesco",
        "benefits_title": "Por que escolher o Seguro de Vida Bradesco?",
        "benefits_subtitle": "A maior seguradora do Brasil com tradição e solidez para proteger sua família.",
        "benefits": [
            {"icon": "🛡️", "title": "Maior Seguradora", "desc": "A solidez e confiança da maior seguradora do Brasil no seu seguro de vida."},
            {"icon": "💰", "title": "Coberturas Flexíveis", "desc": "Monte seu seguro com as coberturas que fazem sentido para você."},
            {"icon": "🏥", "title": "Assistência Funeral", "desc": "Assistência funeral individual ou familiar inclusa."},
            {"icon": "📋", "title": "Invalidez", "desc": "Cobertura para invalidez permanente total ou parcial por acidente."},
            {"icon": "💳", "title": "Diária de Internação", "desc": "Receba diárias em caso de internação hospitalar."},
            {"icon": "👨‍👩‍👧‍👦", "title": "Proteção Familiar", "desc": "Garanta o futuro financeiro da sua família."},
        ],
        "plans_title": "Coberturas Bradesco Vida",
        "plans_subtitle": "Monte seu seguro com as coberturas ideais.",
        "plans": [
            {"name": "Vida Essencial", "type": "Cobertura Básica", "items": ["Morte natural e acidental", "Assistência funeral", "Cobertura 24h", "Sem exames médicos*", "Valores acessíveis"]},
            {"name": "Vida Completo", "type": "Coberturas Amplas", "featured": True, "items": ["Tudo do Essencial +", "Invalidez por acidente", "Diária de internação", "Doenças graves", "Assistência residencial"]},
            {"name": "Vida Premium", "type": "Máxima Proteção", "items": ["Tudo do Completo +", "Invalidez funcional", "Capital elevado", "Assistência completa", "Benefícios exclusivos"]},
        ],
        "network_title": "Coberturas Disponíveis",
        "network_subtitle": "Monte seu seguro de vida com as coberturas ideais para sua necessidade.",
        "network": ["Morte Natural", "Morte Acidental", "Invalidez por Acidente", "Invalidez Funcional", "Doenças Graves", "Diária de Internação", "Assistência Funeral", "Assistência Residencial", "Assistência Pet", "Sorteios Mensais"],
        "faqs": [
            {"q": "Quanto custa o seguro de vida Bradesco?", "a": "A partir de valores acessíveis, variando conforme idade e coberturas escolhidas. Solicite cotação."},
            {"q": "Preciso fazer exame médico?", "a": "Para coberturas até determinados valores, não é necessário exame médico."},
            {"q": "O seguro cobre morte por doença?", "a": "Sim, todos os planos incluem cobertura por morte natural e acidental."},
            {"q": "O que é invalidez funcional?", "a": "Cobertura para quando a pessoa fica impossibilitada de exercer suas atividades do dia a dia."},
            {"q": "Minha família recebe se eu falecer?", "a": "Sim, os beneficiários designados recebem o capital segurado."},
        ],
    },
    {
        "slug": "plano-de-saude-joao-pessoa-sulamerica",
        "title": "SulAmérica João Pessoa | Plano de Saúde PB 2026 | Virtua",
        "meta_description": "Plano de Saúde SulAmérica em João Pessoa e Paraíba. Preços 2026, plano Direto. Individual e empresarial. Cotação grátis.",
        "h1": "SulAmérica Saúde<br>João Pessoa",
        "operator_name": "SulAmérica João Pessoa",
        "hero_subtitle": "A SulAmérica oferece planos com rede credenciada em João Pessoa e Paraíba, incluindo o Plano Direto com preços acessíveis e o Especial com rede ampla.",
        "hero_gradient": "linear-gradient(135deg, #003d7a 0%, #0057a8 50%, #0072d6 100%)",
        "hero_text_color": "#003d7a",
        "accent_color": "#0072d6",
        "badges": ["Corretor Autorizado", "Preços 2026", "João Pessoa e PB", "Plano Direto"],
        "whatsapp_msg": "Olá, gostaria de uma cotação da SulAmérica em João Pessoa",
        "benefits_title": "SulAmérica em João Pessoa",
        "benefits_subtitle": "Qualidade SulAmérica com rede credenciada na Paraíba.",
        "benefits": [
            {"icon": "🏥", "title": "Rede na Paraíba", "desc": "Hospitais e clínicas em João Pessoa e região metropolitana."},
            {"icon": "💰", "title": "Plano Direto", "desc": "Opção econômica SulAmérica com rede regional."},
            {"icon": "📱", "title": "Saúde Ativa", "desc": "App com telemedicina e programas de bem-estar."},
            {"icon": "⭐", "title": "Qualidade ANS", "desc": "SulAmérica entre as mais bem avaliadas."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Planos para empresas paraibanas."},
            {"icon": "🔄", "title": "Portabilidade", "desc": "Aceita migração sem carência."},
        ],
        "plans_title": "Planos SulAmérica em João Pessoa",
        "plans_subtitle": "Opções disponíveis para a Paraíba.",
        "plans": [
            {"name": "SulAmérica Direto PB", "type": "Regional · Enfermaria", "items": ["Rede regional JP", "Enfermaria", "Custo benefício", "Telemedicina 24h", "Saúde Ativa"]},
            {"name": "SulAmérica Especial", "type": "Nacional · Apartamento", "featured": True, "items": ["Rede nacional", "Apartamento", "Reembolso", "Rede premium JP", "Preventivos"]},
            {"name": "SulAmérica Executivo", "type": "Nacional · Premium", "items": ["Rede premium nacional", "Alto reembolso", "Hospitais top", "Internacional", "Assistente pessoal"]},
        ],
        "network_title": "Rede em João Pessoa",
        "network_subtitle": "Hospitais e clínicas credenciados na Paraíba.",
        "network": ["Hospital Unimed JP", "Hospital Samaritano JP", "Laboratórios credenciados", "Centros de Diagnóstico", "Clínicas Especializadas", "Prontos-Socorros 24h", "Maternidades", "Rede em Campina Grande"],
        "faqs": [
            {"q": "A SulAmérica tem plano Direto em João Pessoa?", "a": "Sim! Opção econômica com rede regional na capital paraibana."},
            {"q": "Qual o preço em João Pessoa?", "a": "Varia conforme plano e idade. Solicite cotação."},
            {"q": "Aceita empresas em JP?", "a": "Sim, planos empresariais a partir de 2 vidas."},
        ],
    },
    {
        "slug": "plano-de-saude-hapvida-brasilia",
        "title": "Hapvida Brasília | Plano de Saúde DF 2026 | Virtua Corretora",
        "meta_description": "Plano de Saúde Hapvida em Brasília e DF. Preços 2026, rede própria. Individual e empresarial. Cotação grátis.",
        "h1": "Plano de Saúde Hapvida<br>Brasília e DF",
        "operator_name": "Hapvida Brasília",
        "hero_subtitle": "A Hapvida oferece planos acessíveis em Brasília e Distrito Federal com rede própria e credenciada. Planos individuais e empresariais com preços competitivos.",
        "hero_gradient": "linear-gradient(135deg, #004d00 0%, #006600 50%, #008800 100%)",
        "hero_text_color": "#004d00",
        "accent_color": "#008800",
        "badges": ["Corretor Autorizado", "Preços 2026", "Brasília e DF", "Rede Própria"],
        "whatsapp_msg": "Olá, gostaria de uma cotação do plano Hapvida em Brasília",
        "benefits_title": "Hapvida em Brasília",
        "benefits_subtitle": "Rede própria e credenciada no Distrito Federal e entorno.",
        "benefits": [
            {"icon": "🏥", "title": "Rede no DF", "desc": "Hospitais, clínicas e laboratórios em Brasília e entorno."},
            {"icon": "💰", "title": "Preços Acessíveis", "desc": "Planos competitivos para o mercado de Brasília."},
            {"icon": "📱", "title": "Teleconsulta", "desc": "Consultas online pelo app Hapvida."},
            {"icon": "🔬", "title": "Labs Próprios", "desc": "Exames na rede de laboratórios Hapvida."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Planos para empresas do DF a partir de 2 vidas."},
            {"icon": "🌍", "title": "Entorno Coberto", "desc": "Brasília, Taguatinga, Ceilândia, Águas Claras e entorno."},
        ],
        "plans_title": "Planos Hapvida em Brasília",
        "plans_subtitle": "Opções para pessoa física e empresas no DF.",
        "plans": [
            {"name": "Hapvida Mix DF", "type": "Regional · Enfermaria", "items": ["Rede própria + credenciada DF", "Coparticipação parcial", "Teleconsulta", "Prevenção", "Enfermaria"]},
            {"name": "Hapvida Pleno DF", "type": "Regional · Apartamento", "featured": True, "items": ["Rede completa no DF", "Sem coparticipação rede própria", "Apartamento", "UPAs 24h", "Cobertura completa"]},
            {"name": "Hapvida Nacional", "type": "Nacional · Apartamento", "items": ["Cobertura nacional", "Rede em todo Brasil", "Apartamento", "Especialidades", "Medicina preventiva"]},
        ],
        "network_title": "Rede em Brasília",
        "network_subtitle": "Hospitais e clínicas Hapvida no Distrito Federal.",
        "network": ["Hospital Hapvida Brasília", "UPAs Hapvida DF", "Laboratórios Hapvida", "Centros de Diagnóstico", "Clínicas em Taguatinga", "Rede em Ceilândia", "Águas Claras", "Prontos-Socorros 24h"],
        "faqs": [
            {"q": "Onde a Hapvida atende em Brasília?", "a": "Plano Piloto, Taguatinga, Ceilândia, Águas Claras, Samambaia e entorno."},
            {"q": "Hapvida tem hospital em Brasília?", "a": "Sim, com rede própria e credenciada no DF."},
            {"q": "Aceita MEI em Brasília?", "a": "Sim, empresas MEI a partir de 2 vidas."},
        ],
    },
    {
        "slug": "plano-de-saude-unimed-campos",
        "title": "Unimed Campos | Plano de Saúde 2026 | Virtua Corretora",
        "meta_description": "Plano de Saúde Unimed em Campos dos Goytacazes. Preços 2026. Individual e empresarial. Cotação grátis com corretor autorizado.",
        "h1": "Plano de Saúde Unimed<br>Campos dos Goytacazes",
        "operator_name": "Unimed Campos",
        "hero_subtitle": "A Unimed Norte Fluminense é referência em Campos dos Goytacazes e região, com a tradição da maior cooperativa médica do mundo e ampla rede de médicos cooperados locais.",
        "hero_gradient": "linear-gradient(135deg, #006341 0%, #00874a 50%, #00a85a 100%)",
        "hero_text_color": "#006341",
        "accent_color": "#00874a",
        "badges": ["Corretor Autorizado", "Preços 2026", "Campos dos Goytacazes", "Maior Rede Médica"],
        "whatsapp_msg": "Olá, gostaria de uma cotação da Unimed em Campos",
        "benefits_title": "Unimed em Campos dos Goytacazes",
        "benefits_subtitle": "A tradição Unimed na principal cidade do Norte Fluminense.",
        "benefits": [
            {"icon": "🏥", "title": "Rede em Campos", "desc": "Hospital e clínicas Unimed em Campos dos Goytacazes."},
            {"icon": "👨‍⚕️", "title": "Médicos Cooperados", "desc": "Amplo corpo clínico de médicos cooper ados na região."},
            {"icon": "💚", "title": "Tradição Local", "desc": "Décadas atendendo o Norte Fluminense com qualidade."},
            {"icon": "📱", "title": "Unimed Digital", "desc": "Telemedicina e carteirinha digital pelo app."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Planos para empresas campistas de todos os portes."},
            {"icon": "🌍", "title": "Intercâmbio", "desc": "Use seu plano em outras Unimeds do Brasil."},
        ],
        "plans_title": "Planos Unimed Campos",
        "plans_subtitle": "Opções para pessoa física e empresas em Campos.",
        "plans": [
            {"name": "Unimed Enfermaria", "type": "Regional · Enfermaria", "items": ["Cobertura em Campos e região", "Enfermaria", "Médicos cooperados", "Exames e internações", "Urgência 24h"]},
            {"name": "Unimed Apartamento", "type": "Regional · Apartamento", "featured": True, "items": ["Rede ampla regional", "Apartamento", "Especialidades médicas", "Exames especializados", "Programa preventivo"]},
            {"name": "Unimed Empresarial", "type": "A partir de 2 vidas", "items": ["Condições especiais empresas", "Opção enf. ou apartamento", "Economia vs. individual", "Dependentes inclusos", "MEI aceito"]},
        ],
        "network_title": "Rede Unimed em Campos",
        "network_subtitle": "Hospitais e clínicas na principal cidade do Norte Fluminense.",
        "network": ["Hospital Unimed Campos", "Clínicas Unimed", "Laboratórios", "Centros de Diagnóstico", "Médicos Cooperados", "Prontos-Socorros", "Especialidades", "Intercâmbio Nacional"],
        "faqs": [
            {"q": "Onde fica o Hospital Unimed Campos?", "a": "Em Campos dos Goytacazes. Consulte o endereço atualizado."},
            {"q": "A Unimed Campos aceita MEI?", "a": "Sim, planos empresariais a partir de 2 vidas."},
            {"q": "Posso usar em outra cidade?", "a": "Sim, pelo intercâmbio Unimed para urgências em outras cidades."},
        ],
    },
    {
        "slug": "plano-saude-unimed-macae",
        "title": "Unimed Macaé | Plano de Saúde 2026 | Virtua Corretora",
        "meta_description": "Plano de Saúde Unimed em Macaé e região. Preços 2026. Individual e empresarial. Cotação grátis com corretor autorizado.",
        "h1": "Plano de Saúde Unimed<br>Macaé",
        "operator_name": "Unimed Macaé",
        "hero_subtitle": "A Unimed Macaé é referência em saúde na região dos lagos e norte fluminense, com rede de médicos cooperados atendendo Macaé, Rio das Ostras e cidades vizinhas.",
        "hero_gradient": "linear-gradient(135deg, #006341 0%, #00874a 50%, #00a85a 100%)",
        "hero_text_color": "#006341",
        "accent_color": "#00874a",
        "badges": ["Corretor Autorizado", "Preços 2026", "Macaé e Região", "Unimed"],
        "whatsapp_msg": "Olá, gostaria de uma cotação da Unimed em Macaé",
        "benefits_title": "Unimed em Macaé",
        "benefits_subtitle": "A tradição Unimed na cidade do petróleo.",
        "benefits": [
            {"icon": "🏥", "title": "Rede em Macaé", "desc": "Hospital e clínicas Unimed em Macaé e Rio das Ostras."},
            {"icon": "👨‍⚕️", "title": "Médicos Cooperados", "desc": "Corpo clínico regional de especialistas."},
            {"icon": "💚", "title": "Tradição", "desc": "Unimed consolidada na região."},
            {"icon": "📱", "title": "Unimed Digital", "desc": "Telemedicina e serviços pelo app."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Planos para empresas de Macaé."},
            {"icon": "🌍", "title": "Intercâmbio", "desc": "Atendimento em outras Unimeds do país."},
        ],
        "plans_title": "Planos Unimed Macaé",
        "plans_subtitle": "Opções para pessoa física e empresas em Macaé.",
        "plans": [
            {"name": "Unimed Enfermaria", "type": "Regional · Enfermaria", "items": ["Macaé e Rio das Ostras", "Enfermaria", "Cooperados locais", "Exames", "Urgência 24h"]},
            {"name": "Unimed Apartamento", "type": "Regional · Apartamento", "featured": True, "items": ["Rede ampla regional", "Apartamento", "Especialidades", "Exames especializados", "Preventivo"]},
            {"name": "Unimed Empresarial", "type": "A partir de 2 vidas", "items": ["Especial empresas", "Enfermaria ou apartamento", "Economia", "Dependentes", "MEI aceito"]},
        ],
        "network_title": "Rede Unimed em Macaé",
        "network_subtitle": "Hospitais e clínicas em Macaé e região.",
        "network": ["Hospital Unimed Macaé", "Clínicas Unimed", "Laboratórios", "Centros de Diagnóstico", "Rio das Ostras", "Médicos Cooperados", "Prontos-Socorros", "Intercâmbio Nacional"],
        "faqs": [
            {"q": "A Unimed Macaé atende em Rio das Ostras?", "a": "Sim, a Unimed Macaé oferece cobertura em Macaé e Rio das Ostras."},
            {"q": "Aceita MEI em Macaé?", "a": "Sim, planos empresariais a partir de 2 vidas para MEI."},
            {"q": "Posso usar em outra cidade?", "a": "Sim, intercâmbio Unimed para urgências em todo Brasil."},
        ],
    },
    {
        "slug": "plano-de-saude-caberj-integral-saude",
        "title": "CABERJ Integral Saúde | Plano de Saúde RJ 2026 | Virtua",
        "meta_description": "Plano de Saúde CABERJ Integral Saúde no Rio de Janeiro. Preços 2026. Individual e empresarial. Cotação grátis.",
        "h1": "CABERJ<br>Integral Saúde",
        "operator_name": "CABERJ Integral",
        "hero_subtitle": "A CABERJ Integral Saúde é uma operadora regional do Rio de Janeiro com tradição em atendimento de qualidade e preços competitivos. Planos individuais e empresariais.",
        "hero_gradient": "linear-gradient(135deg, #1a365d 0%, #2a4a7f 50%, #3b5998 100%)",
        "hero_text_color": "#1a365d",
        "accent_color": "#3b5998",
        "badges": ["Corretor Autorizado", "Preços 2026", "Rio de Janeiro", "Tradição Regional"],
        "whatsapp_msg": "Olá, gostaria de uma cotação do plano CABERJ Integral Saúde",
        "benefits_title": "Por que escolher a CABERJ Integral?",
        "benefits_subtitle": "Operadora regional do RJ com tradição e qualidade no atendimento.",
        "benefits": [
            {"icon": "🏥", "title": "Rede no RJ", "desc": "Hospitais, clínicas e laboratórios credenciados no Rio de Janeiro."},
            {"icon": "💰", "title": "Preços Regionais", "desc": "Valores competitivos para o mercado carioca."},
            {"icon": "⭐", "title": "Tradição", "desc": "Operadora consolidada no mercado do Rio de Janeiro."},
            {"icon": "👨‍👩‍👧‍👦", "title": "Individual e Familiar", "desc": "Opções para pessoa física e famílias."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Planos para empresas cariocas."},
            {"icon": "📱", "title": "Atendimento", "desc": "Suporte humanizado e acessível."},
        ],
        "plans_title": "Planos CABERJ Integral Saúde",
        "plans_subtitle": "Opções para o Rio de Janeiro.",
        "plans": [
            {"name": "Integral Enfermaria", "type": "Regional RJ · Enfermaria", "items": ["Cobertura no RJ", "Enfermaria", "Consultas e exames", "Urgência 24h", "Internações"]},
            {"name": "Integral Apartamento", "type": "Regional RJ · Apartamento", "featured": True, "items": ["Rede ampla no RJ", "Apartamento", "Rede credenciada qualificada", "Especialidades", "Cobertura completa"]},
            {"name": "Integral Empresarial", "type": "A partir de 2 vidas", "items": ["Condições especiais", "Economia", "Enfermaria ou apartamento", "Dependentes", "MEI aceito"]},
        ],
        "network_title": "Rede Credenciada CABERJ",
        "network_subtitle": "Hospitais e clínicas no Rio de Janeiro.",
        "network": ["Hospitais credenciados RJ", "Clínicas na capital", "Laboratórios", "Centros de Diagnóstico", "Prontos-Socorros", "Maternidades", "Especialidades", "Grande Rio"],
        "faqs": [
            {"q": "Onde a CABERJ Integral atende?", "a": "No Rio de Janeiro capital e região metropolitana."},
            {"q": "A CABERJ aceita MEI?", "a": "Sim, planos empresariais a partir de 2 vidas."},
            {"q": "Como contratar?", "a": "Ligue (22) 99940-4840 ou envie WhatsApp."},
        ],
    },
]

if __name__ == "__main__":
    print(f"Generating {len(BATCH3)} operator pages (batch 3)...")
    for page in BATCH3:
        path = generate_page(page)
        print(f"  OK {path}")
    print(f"\nDone! {len(BATCH3)} pages created.")
