#!/usr/bin/env python3
"""Batch 4: High-priority pages - telefones, reembolsos, cities (part 1)."""
import sys
sys.path.insert(0, '.')
from generate_operator_pages import generate_page

BATCH4 = [
    {
        "slug": "telefones-odontoprev",
        "title": "Telefones OdontoPrev | SAC e Atendimento 2026 | Virtua",
        "meta_description": "Telefones OdontoPrev atualizados 2026. SAC, ouvidoria, emergência e contato comercial. Números para todo o Brasil.",
        "h1": "Telefones OdontoPrev<br>SAC e Atendimento",
        "operator_name": "OdontoPrev",
        "hero_subtitle": "Encontre todos os telefones da OdontoPrev atualizados: SAC, ouvidoria, central de emergência, boletos e contato comercial para contratar ou tirar dúvidas.",
        "hero_gradient": "linear-gradient(135deg, #0d47a1 0%, #1976d2 50%, #42a5f5 100%)",
        "hero_text_color": "#0d47a1", "accent_color": "#1976d2",
        "badges": ["Atualizado 2026", "SAC", "Ouvidoria", "Emergência"],
        "whatsapp_msg": "Olá, preciso de informações sobre a OdontoPrev",
        "benefits_title": "Canais de Atendimento OdontoPrev",
        "benefits_subtitle": "Todos os telefones e canais para falar com a OdontoPrev.",
        "benefits": [
            {"icon": "📞", "title": "SAC OdontoPrev", "desc": "Central de atendimento: 0800 702 9000. Horário comercial de segunda a sexta."},
            {"icon": "📋", "title": "Ouvidoria", "desc": "Canal de ouvidoria para reclamações e sugestões: 0800 603 1035."},
            {"icon": "🆘", "title": "Emergência 24h", "desc": "Atendimento de emergência odontológica disponível 24 horas."},
            {"icon": "💳", "title": "2ª Via Boleto", "desc": "Emita a 2ª via do boleto pelo site ou app OdontoPrev."},
            {"icon": "📱", "title": "App OdontoPrev", "desc": "Consulte rede credenciada, carteirinha digital e mais pelo app."},
            {"icon": "🦷", "title": "Rede Credenciada", "desc": "Encontre dentistas credenciados pelo site ou telefone."},
        ],
        "plans_title": "Planos OdontoPrev", "plans_subtitle": "Conheça os planos odontológicos OdontoPrev.",
        "plans": [
            {"name": "OdontoPrev Básico", "type": "Nacional · Essencial", "items": ["Consultas", "Prevenção", "Restaurações", "Emergência 24h", "Extrações"]},
            {"name": "OdontoPrev Plus", "type": "Nacional · Completo", "featured": True, "items": ["Tudo do Básico", "Endodontia", "Periodontia", "Cirurgias", "Próteses"]},
            {"name": "OdontoPrev Master", "type": "Nacional · Premium", "items": ["Tudo do Plus", "Ortodontia", "Implantes", "Clareamento", "Cobertura ampla"]},
        ],
        "network_title": "Contatos OdontoPrev",
        "network_subtitle": "Todos os canais de atendimento atualizados.",
        "network": ["SAC: 0800 702 9000", "Ouvidoria: 0800 603 1035", "Emergência 24h", "Site: odontoprev.com.br", "App OdontoPrev", "WhatsApp Virtua: (22) 99940-4840", "E-mail de contato", "Chat online"],
        "faqs": [
            {"q": "Qual o telefone do SAC OdontoPrev?", "a": "0800 702 9000, de segunda a sexta em horário comercial."},
            {"q": "OdontoPrev tem atendimento 24h?", "a": "Sim, para emergências odontológicas."},
            {"q": "Como emitir 2ª via do boleto?", "a": "Pelo site odontoprev.com.br ou app OdontoPrev."},
            {"q": "Como encontro um dentista credenciado?", "a": "Pelo app OdontoPrev ou site, filtrando por cidade e especialidade."},
        ],
    },
    {
        "slug": "telefones-amil-dental",
        "title": "Telefones Amil Dental | SAC e Atendimento 2026 | Virtua",
        "meta_description": "Telefones Amil Dental atualizados 2026. SAC, ouvidoria, emergência e rede credenciada.",
        "h1": "Telefones Amil Dental<br>SAC e Atendimento",
        "operator_name": "Amil Dental",
        "hero_subtitle": "Todos os telefones Amil Dental atualizados: SAC, ouvidoria, emergência, 2ª via de boleto e rede credenciada.",
        "hero_gradient": "linear-gradient(135deg, #003366 0%, #004d99 50%, #0066cc 100%)",
        "hero_text_color": "#003366", "accent_color": "#0066cc",
        "badges": ["Atualizado 2026", "SAC", "Ouvidoria", "Dental"],
        "whatsapp_msg": "Olá, preciso dos telefones da Amil Dental",
        "benefits_title": "Canais de Atendimento Amil Dental",
        "benefits_subtitle": "Todos os contatos da Amil Dental em um só lugar.",
        "benefits": [
            {"icon": "📞", "title": "SAC Amil Dental", "desc": "Central: 0800 726 2645 ou 3003 0435 (capitais). Horário comercial."},
            {"icon": "📋", "title": "Ouvidoria", "desc": "Ouvidoria Amil: 0800 726 2645 opção 7."},
            {"icon": "🆘", "title": "Emergência 24h", "desc": "Atendimento de emergência odontológica 24 horas."},
            {"icon": "💳", "title": "2ª Via Boleto", "desc": "Pelo site amil.com.br ou app Amil."},
            {"icon": "📱", "title": "App Amil", "desc": "Carteirinha digital, rede credenciada e serviços pelo app."},
            {"icon": "🦷", "title": "Rede Credenciada", "desc": "Mais de 26.000 dentistas em todo o Brasil."},
        ],
        "plans_title": "Planos Amil Dental", "plans_subtitle": "Opções de plano odontológico Amil.",
        "plans": [
            {"name": "Amil Dental 100", "type": "Nacional · Básico", "items": ["Consultas e diagnóstico", "Prevenção completa", "Restaurações", "Emergência", "Extrações"]},
            {"name": "Amil Dental 200", "type": "Nacional · Completo", "featured": True, "items": ["Tudo do 100", "Endodontia", "Periodontia", "Cirurgias", "Próteses"]},
            {"name": "Amil Dental 400", "type": "Nacional · Premium", "items": ["Tudo do 200", "Ortodontia", "Implantes", "Clareamento", "Cobertura máxima"]},
        ],
        "network_title": "Contatos Amil Dental",
        "network_subtitle": "Canais de atendimento Amil Dental.",
        "network": ["SAC: 0800 726 2645", "Capitais: 3003 0435", "Ouvidoria: opção 7", "Site: amil.com.br", "App Amil", "WhatsApp Virtua: (22) 99940-4840"],
        "faqs": [
            {"q": "Qual o SAC da Amil Dental?", "a": "0800 726 2645 ou 3003 0435 em capitais."},
            {"q": "A Amil Dental tem emergência 24h?", "a": "Sim, atendimento de emergência odontológica 24h."},
            {"q": "Como achar dentista Amil Dental?", "a": "Pelo app Amil ou site amil.com.br na seção rede credenciada."},
        ],
    },
    {
        "slug": "plano-de-saude-sulamerica-direto-brasilia",
        "title": "SulAmérica Direto Brasília | Preços 2026 | Virtua",
        "meta_description": "Plano SulAmérica Direto em Brasília e DF. Preços 2026. O plano mais acessível da SulAmérica. Cotação grátis.",
        "h1": "SulAmérica Direto<br>Brasília e DF",
        "operator_name": "SulAmérica Direto Brasília",
        "hero_subtitle": "O SulAmérica Direto é o plano mais acessível da SulAmérica em Brasília, com rede credenciada regional selecionada e o programa Saúde Ativa incluso.",
        "hero_gradient": "linear-gradient(135deg, #003d7a 0%, #0057a8 50%, #0072d6 100%)",
        "hero_text_color": "#003d7a", "accent_color": "#0072d6",
        "badges": ["Preços 2026", "Brasília e DF", "Plano Direto", "Mais Acessível"],
        "whatsapp_msg": "Olá, gostaria de cotação do SulAmérica Direto em Brasília",
        "benefits_title": "SulAmérica Direto em Brasília",
        "benefits_subtitle": "O plano mais acessível da SulAmérica no Distrito Federal.",
        "benefits": [
            {"icon": "💰", "title": "Mais Acessível", "desc": "O plano Direto é a opção mais econômica da SulAmérica."},
            {"icon": "🏥", "title": "Rede em Brasília", "desc": "Hospitais e clínicas selecionados no DF."},
            {"icon": "📱", "title": "Saúde Ativa", "desc": "Telemedicina, psicólogo e nutricionista online."},
            {"icon": "⭐", "title": "Qualidade SulAmérica", "desc": "A tradição e segurança da SulAmérica Saúde."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Planos PME a partir de 2 vidas."},
            {"icon": "🔄", "title": "Portabilidade", "desc": "Aceita migração sem carência."},
        ],
        "plans_title": "Planos SulAmérica Direto BSB", "plans_subtitle": "Opções do Direto em Brasília.",
        "plans": [
            {"name": "Direto Enfermaria", "type": "Regional DF · Enfermaria", "items": ["Rede regional DF", "Enfermaria", "Saúde Ativa incluso", "Telemedicina 24h", "Custo acessível"]},
            {"name": "Direto Apartamento", "type": "Regional DF · Apartamento", "featured": True, "items": ["Rede regional DF", "Apartamento", "Saúde Ativa", "Telemedicina", "Cobertura completa"]},
            {"name": "Especial Nacional", "type": "Upgrade · Nacional", "items": ["Rede nacional", "Reembolso", "Apartamento", "Rede premium", "Livre escolha"]},
        ],
        "network_title": "Rede Direto em Brasília", "network_subtitle": "Hospitais e clínicas do plano Direto no DF.",
        "network": ["Hospitais selecionados DF", "Clínicas em Brasília", "Laboratórios credenciados", "Prontos-Socorros", "Taguatinga", "Águas Claras", "Ceilândia", "Entorno DF"],
        "faqs": [
            {"q": "O SulAmérica Direto é bom?", "a": "Sim! É o plano mais acessível da SulAmérica com rede regional selecionada e Saúde Ativa incluso."},
            {"q": "Qual a rede do Direto em Brasília?", "a": "Rede regional com hospitais e clínicas selecionados no DF."},
            {"q": "O Direto tem reembolso?", "a": "Não. Para reembolso, considere o Especial ou Executivo."},
        ],
    },
    {
        "slug": "plano-de-saude-bh-sulamerica-saude-direto",
        "title": "SulAmérica Direto BH | Preços 2026 | Virtua Corretora",
        "meta_description": "Plano SulAmérica Direto em BH e Minas Gerais. Preços 2026. Rede regional em Belo Horizonte. Cotação grátis.",
        "h1": "SulAmérica Direto<br>Belo Horizonte",
        "operator_name": "SulAmérica Direto BH",
        "hero_subtitle": "O SulAmérica Direto é a opção mais acessível em Belo Horizonte, com rede regional selecionada e o programa Saúde Ativa com telemedicina inclusa.",
        "hero_gradient": "linear-gradient(135deg, #003d7a 0%, #0057a8 50%, #0072d6 100%)",
        "hero_text_color": "#003d7a", "accent_color": "#0072d6",
        "badges": ["Preços 2026", "Belo Horizonte", "Plano Direto", "Mais Acessível"],
        "whatsapp_msg": "Olá, gostaria de cotação do SulAmérica Direto em BH",
        "benefits_title": "SulAmérica Direto em BH",
        "benefits_subtitle": "O plano mais acessível da SulAmérica em Minas Gerais.",
        "benefits": [
            {"icon": "💰", "title": "Mais Acessível", "desc": "Menor mensalidade SulAmérica para BH."},
            {"icon": "🏥", "title": "Rede em BH", "desc": "Hospitais e clínicas selecionados em Belo Horizonte e região."},
            {"icon": "📱", "title": "Saúde Ativa", "desc": "Telemedicina e programas de bem-estar inclusos."},
            {"icon": "⭐", "title": "Tradição SulAmérica", "desc": "Qualidade e segurança da SulAmérica."},
            {"icon": "🏢", "title": "Empresarial", "desc": "PME a partir de 2 vidas."},
            {"icon": "🔄", "title": "Portabilidade", "desc": "Migre sem carência."},
        ],
        "plans_title": "Planos Direto em BH", "plans_subtitle": "Opções SulAmérica Direto para Belo Horizonte.",
        "plans": [
            {"name": "Direto Enfermaria", "type": "Regional MG · Enfermaria", "items": ["Rede regional BH", "Enfermaria", "Saúde Ativa", "Telemedicina", "Custo acessível"]},
            {"name": "Direto Apartamento", "type": "Regional MG · Apartamento", "featured": True, "items": ["Rede regional BH", "Apartamento", "Saúde Ativa", "Cobertura completa", "Telemedicina"]},
            {"name": "Especial Nacional", "type": "Upgrade · Nacional", "items": ["Rede nacional", "Reembolso", "Hospitais premium", "Apartamento", "Livre escolha"]},
        ],
        "network_title": "Rede em Belo Horizonte", "network_subtitle": "Hospitais e clínicas do plano Direto em BH.",
        "network": ["Hospitais em BH", "Clínicas credenciadas", "Laboratórios", "Prontos-Socorros", "Região metropolitana BH", "Contagem", "Betim", "Nova Lima"],
        "faqs": [
            {"q": "Qual o preço do Direto em BH?", "a": "Solicite cotação para valores atualizados 2026."},
            {"q": "Onde o Direto atende em BH?", "a": "Belo Horizonte e região metropolitana."},
            {"q": "O Direto BH tem reembolso?", "a": "Não, o Direto é somente rede credenciada."},
        ],
    },
    {
        "slug": "reembolso-intermedica",
        "title": "Reembolso Intermédica | Como Funciona 2026 | Virtua",
        "meta_description": "Reembolso Intermédica GNDI 2026. Como solicitar, prazos, valores e planos com reembolso. Guia completo.",
        "h1": "Reembolso<br>Intermédica GNDI",
        "operator_name": "reembolso Intermédica",
        "hero_subtitle": "Saiba como funciona o reembolso nos planos Intermédica GNDI, quais planos oferecem, como solicitar e os prazos de processamento.",
        "hero_gradient": "linear-gradient(135deg, #1a1a3e 0%, #2d2d6b 50%, #4a3f8f 100%)",
        "hero_text_color": "#1a1a3e", "accent_color": "#4a3f8f",
        "badges": ["Guia Completo", "Atualizado 2026", "Como Solicitar", "Prazos"],
        "whatsapp_msg": "Olá, preciso saber sobre reembolso Intermédica",
        "benefits_title": "Reembolso Intermédica: Como Funciona",
        "benefits_subtitle": "Guia completo sobre reembolso nos planos GNDI.",
        "benefits": [
            {"icon": "💳", "title": "Plano Advance 600", "desc": "O Advance 600 nacional é o plano Intermédica que oferece reembolso."},
            {"icon": "📋", "title": "Documentação", "desc": "Nota fiscal e relatório médico são necessários para solicitar."},
            {"icon": "📱", "title": "Pelo App", "desc": "Solicite reembolso pelo app GNDI Easy."},
            {"icon": "⏰", "title": "Prazo", "desc": "Processamento em até 30 dias úteis."},
            {"icon": "💰", "title": "Tabela de Valores", "desc": "O reembolso segue a tabela do seu plano por procedimento."},
            {"icon": "🏥", "title": "Rede + Reembolso", "desc": "Use a rede credenciada sem custo ou reembolse fora dela."},
        ],
        "plans_title": "Planos com Reembolso", "plans_subtitle": "Nem todos os planos Intermédica têm reembolso.",
        "plans": [
            {"name": "Smart 200 / 500", "type": "SEM reembolso", "items": ["Planos regionais/estaduais", "Somente rede credenciada", "Não oferece reembolso", "Menor mensalidade", "Ideal para rede própria"]},
            {"name": "Advance 600", "type": "COM reembolso", "featured": True, "items": ["Plano nacional", "Reembolso disponível", "Rede + livre escolha", "Tabela de reembolso", "Melhor cobertura"]},
            {"name": "Advance 600 Premium", "type": "Reembolso Diferenciado", "items": ["Nacional premium", "Maior tabela reembolso", "Rede ampla premium", "Melhores hospitais", "Cobertura máxima"]},
        ],
        "network_title": "Como Solicitar Reembolso", "network_subtitle": "Passo a passo para reembolso Intermédica.",
        "network": ["1. Atenda-se fora da rede", "2. Peça nota fiscal", "3. Obtenha relatório médico", "4. Abra o app GNDI Easy", "5. Envie documentos", "6. Aguarde análise", "7. Receba o reembolso", "Prazo: até 30 dias"],
        "faqs": [
            {"q": "O Smart 200 tem reembolso?", "a": "Não. Somente o Advance 600 possui opção de reembolso."},
            {"q": "Como solicitar reembolso?", "a": "Pelo app GNDI Easy, na seção de reembolso, anexando nota fiscal e relatório."},
            {"q": "Qual o prazo?", "a": "Até 30 dias úteis, mas geralmente é mais rápido."},
            {"q": "Quanto a Intermédica reembolsa?", "a": "Conforme tabela de reembolso do seu plano, variando por procedimento."},
        ],
    },
    {
        "slug": "simulacao-seguro-de-vida",
        "title": "Simulação Seguro de Vida | Cotação Online 2026 | Virtua",
        "meta_description": "Faça uma simulação gratuita de seguro de vida 2026. Compare Bradesco, Porto Seguro, SulAmérica e mais. Cotação sem compromisso.",
        "h1": "Simulação de<br>Seguro de Vida",
        "operator_name": "seguro de vida",
        "hero_subtitle": "Compare as melhores seguradoras e encontre o seguro de vida ideal para proteger sua família. Simulação gratuita e sem compromisso com corretor especializado.",
        "hero_gradient": "linear-gradient(135deg, #1a1a3e 0%, #2d4a6b 50%, #3b6f8f 100%)",
        "hero_text_color": "#1a1a3e", "accent_color": "#2d4a6b",
        "badges": ["Simulação Grátis", "Sem Compromisso", "+10 Seguradoras", "Cotação Online"],
        "whatsapp_msg": "Olá, gostaria de fazer uma simulação de seguro de vida",
        "benefits_title": "Por que contratar um Seguro de Vida?",
        "benefits_subtitle": "Proteção financeira essencial para você e sua família.",
        "benefits": [
            {"icon": "🛡️", "title": "Proteção Familiar", "desc": "Garanta o futuro financeiro da sua família em caso de imprevistos."},
            {"icon": "💰", "title": "A partir de R$30/mês", "desc": "Seguros acessíveis que cabem no seu orçamento."},
            {"icon": "🏥", "title": "Cobertura Ampla", "desc": "Morte, invalidez, doenças graves e assistências inclusas."},
            {"icon": "📋", "title": "Sem Burocracia", "desc": "Contratação simplificada, muitas vezes sem exame médico."},
            {"icon": "💳", "title": "Resgate", "desc": "Alguns planos permitem resgate de parte do valor pago."},
            {"icon": "👨‍👩‍👧‍👦", "title": "Assistência Funeral", "desc": "Assistência funeral individual ou familiar inclusa."},
        ],
        "plans_title": "Seguradoras Parceiras", "plans_subtitle": "Comparamos as melhores opções para você.",
        "plans": [
            {"name": "Bradesco Vida", "type": "Maior Seguradora", "items": ["Morte e invalidez", "Assistência funeral", "Doenças graves", "Cobertura flexível", "Sorteios mensais"]},
            {"name": "Porto Seguro Vida", "type": "Tradição e Solidez", "featured": True, "items": ["Morte e invalidez", "Diária de internação", "Assistências completas", "Resgate disponível", "App Porto"]},
            {"name": "SulAmérica Vida", "type": "Cobertura Premium", "items": ["Morte e invalidez", "Doenças graves", "Alto capital segurado", "Coberturas flexíveis", "Assistência completa"]},
        ],
        "network_title": "Seguradoras Disponíveis", "network_subtitle": "Trabalhamos com as melhores seguradoras do mercado.",
        "network": ["Bradesco Seguros", "Porto Seguro", "SulAmérica", "MetLife", "Prudential", "Zurich", "Tokio Marine", "Mapfre", "Icatu", "MAG Seguros"],
        "faqs": [
            {"q": "Quanto custa um seguro de vida?", "a": "A partir de R$30/mês, variando conforme idade, capital e coberturas."},
            {"q": "Preciso fazer exame médico?", "a": "Para capitais menores, geralmente não. Para valores altos, pode ser necessário."},
            {"q": "O seguro cobre morte por doença?", "a": "Sim, tanto morte natural quanto acidental."},
            {"q": "Posso cancelar a qualquer momento?", "a": "Sim, sem multas. Alguns planos oferecem resgate parcial."},
            {"q": "A simulação é gratuita?", "a": "Sim! Totalmente gratuita e sem compromisso."},
        ],
    },
    {
        "slug": "plano-de-saude-sulamerica-direto-sampa",
        "title": "SulAmérica Direto São Paulo | Preços 2026 | Virtua",
        "meta_description": "Plano SulAmérica Direto em São Paulo. Preços 2026. Rede regional SP. Individual e empresarial. Cotação grátis.",
        "h1": "SulAmérica Direto<br>São Paulo",
        "operator_name": "SulAmérica Direto SP",
        "hero_subtitle": "O SulAmérica Direto é a opção mais acessível em São Paulo, com rede credenciada regional selecionada, telemedicina e o programa Saúde Ativa completo.",
        "hero_gradient": "linear-gradient(135deg, #003d7a 0%, #0057a8 50%, #0072d6 100%)",
        "hero_text_color": "#003d7a", "accent_color": "#0072d6",
        "badges": ["Preços 2026", "São Paulo", "Plano Direto", "Mais Acessível"],
        "whatsapp_msg": "Olá, gostaria de cotação do SulAmérica Direto em SP",
        "benefits_title": "SulAmérica Direto em São Paulo",
        "benefits_subtitle": "O plano mais acessível da SulAmérica na capital paulista.",
        "benefits": [
            {"icon": "💰", "title": "Mais Acessível SP", "desc": "Menor mensalidade SulAmérica em São Paulo."},
            {"icon": "🏥", "title": "Rede em SP", "desc": "Hospitais e clínicas selecionados na Grande São Paulo."},
            {"icon": "📱", "title": "Saúde Ativa", "desc": "Telemedicina e programas de bem-estar."},
            {"icon": "⭐", "title": "Qualidade", "desc": "Tradição SulAmérica no atendimento."},
            {"icon": "🏢", "title": "Empresarial", "desc": "PME a partir de 2 vidas."},
            {"icon": "🔄", "title": "Portabilidade", "desc": "Migre sem carência."},
        ],
        "plans_title": "Planos Direto SP", "plans_subtitle": "Opções SulAmérica Direto para São Paulo.",
        "plans": [
            {"name": "Direto Enfermaria SP", "type": "Regional SP · Enfermaria", "items": ["Rede regional SP", "Enfermaria", "Saúde Ativa", "Telemedicina", "Custos acessíveis"]},
            {"name": "Direto Apartamento SP", "type": "Regional SP · Apartamento", "featured": True, "items": ["Rede regional SP", "Apartamento", "Saúde Ativa", "Telemedicina", "Cobertura completa"]},
            {"name": "Especial Nacional", "type": "Upgrade · Nacional", "items": ["Rede nacional", "Reembolso disponível", "Premium", "Apartamento", "Livre escolha"]},
        ],
        "network_title": "Rede em São Paulo", "network_subtitle": "Rede regional do Direto em SP.",
        "network": ["Hospitais em SP capital", "Clínicas credenciadas", "Laboratórios", "ABCD paulista", "Guarulhos", "Osasco", "Campinas", "Santos"],
        "faqs": [
            {"q": "O Direto SP atende na Grande SP?", "a": "Sim, incluindo capital, ABCD, Guarulhos e Osasco."},
            {"q": "O Direto tem reembolso?", "a": "Não. Para reembolso, considere o Especial ou Executivo."},
            {"q": "Quanto custa o Direto SP?", "a": "Solicite cotação para valores atualizados 2026."},
        ],
    },
    {
        "slug": "plano-de-saude-bradesco",
        "title": "Plano de Saúde Bradesco | Preços 2026 | Virtua Corretora",
        "meta_description": "Plano de Saúde Bradesco Saúde 2026. Individual e empresarial. Rede premium. Cotação grátis com corretor autorizado.",
        "h1": "Plano de Saúde<br>Bradesco Saúde",
        "operator_name": "Bradesco Saúde",
        "hero_subtitle": "A Bradesco Saúde é uma das mais tradicionais operadoras do Brasil, com rede credenciada premium e planos nacionais com excelente cobertura.",
        "hero_gradient": "linear-gradient(135deg, #8B0000 0%, #CC0000 50%, #FF1A1A 100%)",
        "hero_text_color": "#8B0000", "accent_color": "#CC0000",
        "badges": ["Corretor Autorizado", "Preços 2026", "Nacional", "Rede Premium"],
        "whatsapp_msg": "Olá, gostaria de cotação do plano Bradesco Saúde",
        "benefits_title": "Por que escolher a Bradesco Saúde?",
        "benefits_subtitle": "Tradição e qualidade da marca Bradesco na sua saúde.",
        "benefits": [
            {"icon": "⭐", "title": "Tradição Bradesco", "desc": "A solidez de uma das maiores marcas do Brasil."},
            {"icon": "🏥", "title": "Rede Premium", "desc": "Melhores hospitais como Einstein, Sírio-Libanês e Rede D'Or."},
            {"icon": "💳", "title": "Reembolso", "desc": "Opções de reembolso para livre escolha médica."},
            {"icon": "📱", "title": "App Bradesco Saúde", "desc": "Telemedicina, carteirinha digital e serviços online."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Para empresas de todos os portes."},
            {"icon": "🌍", "title": "Nacional", "desc": "Cobertura em todo o Brasil."},
        ],
        "plans_title": "Planos Bradesco Saúde", "plans_subtitle": "Opções de planos Bradesco.",
        "plans": [
            {"name": "Bradesco Efetivo", "type": "Nacional · Enfermaria", "items": ["Nacional", "Enfermaria", "Rede credenciada ampla", "Telemedicina", "Programa preventivo"]},
            {"name": "Bradesco Top Nacional", "type": "Nacional · Apartamento", "featured": True, "items": ["Rede premium nacional", "Apartamento", "Reembolso", "Hospitais referência", "Cobertura completa"]},
            {"name": "Bradesco Top Plus", "type": "Nacional · Premium", "items": ["Rede premium máxima", "Alto reembolso", "Einstein, Sírio-Libanês", "Cobertura internacional", "Assistente pessoal"]},
        ],
        "network_title": "Rede Bradesco Saúde", "network_subtitle": "Hospitais referência em todo o Brasil.",
        "network": ["Hospital Einstein", "Sírio-Libanês", "Rede D'Or", "Copa D'Or", "Samaritano", "Hospital Vitória", "Labs a+", "Dasa", "Prontos-Socorros", "Maternidades"],
        "faqs": [
            {"q": "Qual o SAC Bradesco Saúde?", "a": "SAC: 0800 727 9966. Para contratar: (22) 99940-4840."},
            {"q": "A Bradesco Saúde tem plano individual?", "a": "A Bradesco opera mais com planos empresariais e por adesão. Consulte disponibilidade."},
            {"q": "Quanto custa o Bradesco Saúde?", "a": "Varia conforme plano, idade e região. Solicite cotação."},
            {"q": "Bradesco Saúde tem reembolso?", "a": "Sim, nos planos Top Nacional e Top Plus."},
        ],
    },
]

if __name__ == "__main__":
    print(f"Generating {len(BATCH4)} pages (batch 4)...")
    for page in BATCH4:
        path = generate_page(page)
        print(f"  OK {path}")
    print(f"\nDone! {len(BATCH4)} pages created.")
