#!/usr/bin/env python3
"""Batch 5: Last 7 high-priority pages."""
import sys
sys.path.insert(0, '.')
from generate_operator_pages import generate_page

BATCH5 = [
    {
        "slug": "rede-credenciada-sulamerica-odonto",
        "title": "Rede Credenciada SulAmérica Odonto 2026 | Virtua",
        "meta_description": "Rede credenciada SulAmérica Odonto 2026. Encontre dentistas credenciados. Cobertura nacional.",
        "h1": "Rede Credenciada<br>SulAmérica Odonto",
        "operator_name": "SulAmérica Odonto",
        "hero_subtitle": "Encontre dentistas e clínicas credenciadas do plano odontológico SulAmérica em todo o Brasil. Rede ampla com profissionais qualificados.",
        "hero_gradient": "linear-gradient(135deg, #003d7a 0%, #0057a8 50%, #0072d6 100%)",
        "hero_text_color": "#003d7a", "accent_color": "#0072d6",
        "badges": ["Atualizado 2026", "Nacional", "Dentistas Credenciados", "SulAmérica"],
        "whatsapp_msg": "Olá, preciso de informações sobre a rede SulAmérica Odonto",
        "benefits_title": "Rede SulAmérica Odonto",
        "benefits_subtitle": "Ampla rede de dentistas em todo o Brasil.",
        "benefits": [
            {"icon": "🦷", "title": "Rede Nacional", "desc": "Dentistas credenciados em todas as capitais e principais cidades."},
            {"icon": "📱", "title": "Consulta Online", "desc": "Busque dentistas pelo site ou app SulAmérica por localização."},
            {"icon": "⭐", "title": "Profissionais Qualificados", "desc": "Rede credenciada com rigoroso processo de seleção."},
            {"icon": "🏥", "title": "Especialidades", "desc": "Clínicos, ortodontistas, endodontistas, periodontistas e mais."},
            {"icon": "📋", "title": "Cobertura Completa", "desc": "De prevenção a tratamentos complexos como implantes."},
            {"icon": "💰", "title": "Sem Custo Extra", "desc": "Procedimentos cobertos sem cobrança adicional na rede."},
        ],
        "plans_title": "Planos SulAmérica Odonto", "plans_subtitle": "Opções de planos odontológicos.",
        "plans": [
            {"name": "Odonto Básico", "type": "Nacional", "items": ["Consultas", "Prevenção", "Restaurações", "Emergência", "Extrações"]},
            {"name": "Odonto Plus", "type": "Nacional · Completo", "featured": True, "items": ["Tudo do Básico", "Endodontia", "Periodontia", "Cirurgias", "Próteses"]},
            {"name": "Odonto Premium", "type": "Nacional · Premium", "items": ["Tudo do Plus", "Ortodontia", "Implantes", "Clareamento", "Cobertura máxima"]},
        ],
        "network_title": "Como Encontrar Dentistas", "network_subtitle": "Passo a passo para encontrar um dentista credenciado.",
        "network": ["Site sulamerica.com.br", "App SulAmérica Saúde", "Filtro por cidade", "Filtro por especialidade", "WhatsApp Virtua", "Telefone SAC"],
        "faqs": [
            {"q": "Como encontro um dentista SulAmérica Odonto?", "a": "Pelo app SulAmérica ou site sulamerica.com.br na seção rede credenciada."},
            {"q": "A rede é a mesma em todo Brasil?", "a": "A rede varia por cidade, mas há cobertura em todas as capitais e principais cidades."},
            {"q": "Posso trocar de dentista?", "a": "Sim, você pode consultar qualquer dentista credenciado do seu plano."},
        ],
    },
    {
        "slug": "telefones-assim-saude",
        "title": "Telefones Assim Saúde | SAC e Atendimento 2026 | Virtua",
        "meta_description": "Telefones Assim Saúde atualizados 2026. SAC, ouvidoria, emergência e contato.",
        "h1": "Telefones Assim Saúde<br>SAC e Atendimento",
        "operator_name": "Assim Saúde",
        "hero_subtitle": "Todos os telefones da Assim Saúde atualizados: SAC, ouvidoria, emergência, boletos e contato para contratar.",
        "hero_gradient": "linear-gradient(135deg, #1a365d 0%, #2a4a7f 50%, #3b5998 100%)",
        "hero_text_color": "#1a365d", "accent_color": "#3b5998",
        "badges": ["Atualizado 2026", "SAC", "Ouvidoria", "Emergência"],
        "whatsapp_msg": "Olá, preciso de informações sobre a Assim Saúde",
        "benefits_title": "Canais de Atendimento Assim Saúde",
        "benefits_subtitle": "Todos os contatos da Assim Saúde.",
        "benefits": [
            {"icon": "📞", "title": "SAC Assim Saúde", "desc": "Central de atendimento: 0800 728 8300."},
            {"icon": "📋", "title": "Ouvidoria", "desc": "Canal de ouvidoria para reclamações e sugestões."},
            {"icon": "🆘", "title": "Emergência 24h", "desc": "Pronto-socorro e emergência disponíveis 24h."},
            {"icon": "💳", "title": "2ª Via Boleto", "desc": "Emita a 2ª via pelo site ou app Assim Saúde."},
            {"icon": "📱", "title": "App Assim", "desc": "Rede credenciada, carteirinha e serviços pelo app."},
            {"icon": "🏥", "title": "Rede Credenciada", "desc": "Encontre médicos e hospitais credenciados."},
        ],
        "plans_title": "Planos Assim Saúde", "plans_subtitle": "Opções da Assim Saúde.",
        "plans": [
            {"name": "Assim Básico", "type": "Regional · Enfermaria", "items": ["Cobertura regional", "Enfermaria", "Consultas e exames", "Urgência 24h", "Internações"]},
            {"name": "Assim Completo", "type": "Regional · Apartamento", "featured": True, "items": ["Rede ampla regional", "Apartamento", "Especialidades", "Exames especializados", "Cobertura completa"]},
            {"name": "Assim Empresarial", "type": "A partir de 2 vidas", "items": ["Condições especiais", "Economia", "Opções flexíveis", "Dependentes", "MEI aceito"]},
        ],
        "network_title": "Contatos Assim Saúde", "network_subtitle": "Canais de atendimento.",
        "network": ["SAC: 0800 728 8300", "Ouvidoria", "Site: asssimsaude.com.br", "App Assim Saúde", "WhatsApp Virtua: (22) 99940-4840"],
        "faqs": [
            {"q": "Qual o SAC da Assim Saúde?", "a": "0800 728 8300."},
            {"q": "Onde a Assim Saúde atende?", "a": "Presente no Espírito Santo e Rio de Janeiro."},
            {"q": "A Assim aceita MEI?", "a": "Sim, planos empresariais a partir de 2 vidas."},
        ],
    },
    {
        "slug": "telefones-intermedica",
        "title": "Telefones Intermédica | SAC e Atendimento 2026 | Virtua",
        "meta_description": "Telefones Intermédica GNDI 2026. SAC, ouvidoria, emergência, boleto e contato comercial.",
        "h1": "Telefones Intermédica<br>SAC e Atendimento",
        "operator_name": "Intermédica",
        "hero_subtitle": "Todos os telefones da Intermédica GNDI atualizados: SAC, ouvidoria, central de emergência, 2ª via boleto e contato comercial.",
        "hero_gradient": "linear-gradient(135deg, #1a1a3e 0%, #2d2d6b 50%, #4a3f8f 100%)",
        "hero_text_color": "#1a1a3e", "accent_color": "#4a3f8f",
        "badges": ["Atualizado 2026", "SAC", "Ouvidoria", "GNDI"],
        "whatsapp_msg": "Olá, preciso de telefones da Intermédica",
        "benefits_title": "Canais de Atendimento Intermédica",
        "benefits_subtitle": "Todos os contatos da Intermédica GNDI.",
        "benefits": [
            {"icon": "📞", "title": "SAC Intermédica", "desc": "Central: 4090-1750 ou 0800 409 1750 (todo Brasil)."},
            {"icon": "📋", "title": "Ouvidoria", "desc": "Ouvidoria GNDI: 0800 877 1799."},
            {"icon": "🆘", "title": "Emergência 24h", "desc": "Prontos-socorros e UPAs próprios 24 horas."},
            {"icon": "💳", "title": "2ª Via Boleto", "desc": "Área do beneficiário em gndi.com.br ou app GNDI Easy."},
            {"icon": "📱", "title": "App GNDI Easy", "desc": "Telemedicina, carteirinha, agendamentos e serviços."},
            {"icon": "🏥", "title": "Rede Credenciada", "desc": "31 hospitais próprios + ampla rede credenciada."},
        ],
        "plans_title": "Planos Intermédica", "plans_subtitle": "Conheça os planos GNDI.",
        "plans": [
            {"name": "Smart 200", "type": "Regional · Enfermaria", "items": ["Regional RJ ou SP", "Enfermaria", "Rede própria", "Coparticipação", "Custo acessível"]},
            {"name": "Smart 500", "type": "Estadual · Apartamento", "featured": True, "items": ["Estadual RJ ou SP", "Opção apartamento", "Rede ampla", "Interior coberto", "GNDI Easy"]},
            {"name": "Advance 600", "type": "Nacional · Apartamento", "items": ["Nacional", "Apartamento", "Reembolso", "Interclube", "Medicina preventiva"]},
        ],
        "network_title": "Contatos Intermédica", "network_subtitle": "Todos os canais.",
        "network": ["SAC: 4090-1750", "SAC: 0800 409 1750", "Ouvidoria: 0800 877 1799", "Site: gndi.com.br", "App GNDI Easy", "WhatsApp Virtua: (22) 99940-4840", "Corretor: (22) 99940-4840"],
        "faqs": [
            {"q": "Qual o SAC da Intermédica?", "a": "4090-1750 ou 0800 409 1750."},
            {"q": "A Intermédica tem app?", "a": "Sim, o GNDI Easy com telemedicina e serviços."},
            {"q": "Como emitir 2ª via boleto?", "a": "Em gndi.com.br na área do beneficiário ou pelo app GNDI Easy."},
        ],
    },
    {
        "slug": "plano-de-saude-sulamerica-direto-salvador",
        "title": "SulAmérica Direto Salvador | Preços 2026 | Virtua",
        "meta_description": "SulAmérica Direto em Salvador e Bahia. Preços 2026. Rede regional. Cotação grátis.",
        "h1": "SulAmérica Direto<br>Salvador e Bahia",
        "operator_name": "SulAmérica Direto Salvador",
        "hero_subtitle": "O SulAmérica Direto é o plano mais acessível em Salvador, com rede regional selecionada e programa Saúde Ativa incluso.",
        "hero_gradient": "linear-gradient(135deg, #003d7a 0%, #0057a8 50%, #0072d6 100%)",
        "hero_text_color": "#003d7a", "accent_color": "#0072d6",
        "badges": ["Preços 2026", "Salvador e BA", "Plano Direto", "Mais Acessível"],
        "whatsapp_msg": "Olá, gostaria do SulAmérica Direto em Salvador",
        "benefits_title": "SulAmérica Direto em Salvador",
        "benefits_subtitle": "O plano mais acessível da SulAmérica na Bahia.",
        "benefits": [
            {"icon": "💰", "title": "Mais Acessível BA", "desc": "Menor mensalidade SulAmérica em Salvador."},
            {"icon": "🏥", "title": "Rede em Salvador", "desc": "Hospitais e clínicas selecionados."},
            {"icon": "📱", "title": "Saúde Ativa", "desc": "Telemedicina e bem-estar inclusos."},
            {"icon": "⭐", "title": "Qualidade", "desc": "Tradição SulAmérica."},
            {"icon": "🏢", "title": "Empresarial", "desc": "PME a partir de 2 vidas."},
            {"icon": "🔄", "title": "Portabilidade", "desc": "Migre sem carência."},
        ],
        "plans_title": "Planos Direto Salvador", "plans_subtitle": "Opções para a Bahia.",
        "plans": [
            {"name": "Direto Enfermaria BA", "type": "Regional · Enfermaria", "items": ["Rede regional Salvador", "Enfermaria", "Saúde Ativa", "Telemedicina", "Acessível"]},
            {"name": "Direto Apartamento BA", "type": "Regional · Apartamento", "featured": True, "items": ["Rede Salvador", "Apartamento", "Saúde Ativa", "Cobertura completa", "Melhor opção"]},
            {"name": "Especial Nacional", "type": "Upgrade", "items": ["Rede nacional", "Reembolso", "Premium", "Livre escolha", "Apartamento"]},
        ],
        "network_title": "Rede em Salvador", "network_subtitle": "Hospitais do Direto na Bahia.",
        "network": ["Hospitais em Salvador", "Clínicas credenciadas", "Laboratórios", "Prontos-Socorros", "Lauro de Freitas", "Camaçari", "Feira de Santana"],
        "faqs": [
            {"q": "O Direto Salvador é bom?", "a": "Sim! Rede regional selecionada com Saúde Ativa incluso."},
            {"q": "Tem reembolso?", "a": "Não, o Direto é somente rede credenciada."},
        ],
    },
    {
        "slug": "plano-de-saude-hapvida-manaus",
        "title": "Hapvida Manaus | Plano de Saúde AM 2026 | Virtua",
        "meta_description": "Plano Hapvida em Manaus e Amazonas. Preços 2026. Rede própria. Cotação grátis.",
        "h1": "Plano de Saúde Hapvida<br>Manaus e Amazonas",
        "operator_name": "Hapvida Manaus",
        "hero_subtitle": "A Hapvida é a principal operadora de saúde em Manaus e Amazonas, com hospitais e laboratórios próprios e preços acessíveis.",
        "hero_gradient": "linear-gradient(135deg, #004d00 0%, #006600 50%, #008800 100%)",
        "hero_text_color": "#004d00", "accent_color": "#008800",
        "badges": ["Preços 2026", "Manaus e AM", "Rede Própria", "Hapvida"],
        "whatsapp_msg": "Olá, gostaria de cotação Hapvida em Manaus",
        "benefits_title": "Hapvida em Manaus",
        "benefits_subtitle": "A maior rede de saúde do Amazonas.",
        "benefits": [
            {"icon": "🏥", "title": "Rede Própria AM", "desc": "Hospitais e labs próprios em Manaus."},
            {"icon": "💰", "title": "Melhor Preço AM", "desc": "Planos acessíveis para Manaus."},
            {"icon": "📱", "title": "Teleconsulta", "desc": "Consultas online pelo app."},
            {"icon": "🔬", "title": "Labs Próprios", "desc": "Exames com rapidez."},
            {"icon": "🏢", "title": "Empresarial", "desc": "Para empresas do AM."},
            {"icon": "🌍", "title": "Cobertura", "desc": "Manaus e região metropolitana."},
        ],
        "plans_title": "Planos Hapvida Manaus", "plans_subtitle": "Para pessoa física e empresas.",
        "plans": [
            {"name": "Hapvida Mix AM", "type": "Regional · Enfermaria", "items": ["Rede própria Manaus", "Coparticipação", "Teleconsulta", "Prevenção", "Enfermaria"]},
            {"name": "Hapvida Pleno AM", "type": "Regional · Apartamento", "featured": True, "items": ["Rede completa AM", "Apartamento", "Sem copart. rede própria", "UPAs 24h", "Cobertura completa"]},
            {"name": "Hapvida Nacional", "type": "Nacional", "items": ["Todo Brasil", "Apartamento", "Rede nacional", "Especialidades", "Preventivo"]},
        ],
        "network_title": "Rede em Manaus", "network_subtitle": "Hospitais Hapvida no Amazonas.",
        "network": ["Hospital Hapvida Manaus", "UPAs Hapvida AM", "Laboratórios", "Centros Diagnóstico", "Clínicas", "Prontos-Socorros 24h"],
        "faqs": [
            {"q": "Hapvida tem hospital em Manaus?", "a": "Sim, rede própria com hospitais e UPAs."},
            {"q": "Aceita MEI em Manaus?", "a": "Sim, a partir de 2 vidas."},
        ],
    },
    {
        "slug": "reembolso-amil",
        "title": "Reembolso Amil | Como Funciona 2026 | Virtua Corretora",
        "meta_description": "Reembolso Amil 2026. Como solicitar, prazos, valores e planos. Guia completo.",
        "h1": "Reembolso<br>Amil Saúde",
        "operator_name": "reembolso Amil",
        "hero_subtitle": "Entenda como funciona o reembolso nos planos Amil, quais planos oferecem, como solicitar pelo app e os prazos de processamento.",
        "hero_gradient": "linear-gradient(135deg, #003366 0%, #004d99 50%, #0066cc 100%)",
        "hero_text_color": "#003366", "accent_color": "#0066cc",
        "badges": ["Guia Completo", "Atualizado 2026", "Como Solicitar", "Prazos"],
        "whatsapp_msg": "Olá, preciso saber sobre reembolso Amil",
        "benefits_title": "Reembolso Amil: Como Funciona",
        "benefits_subtitle": "Guia completo sobre reembolso nos planos Amil.",
        "benefits": [
            {"icon": "💳", "title": "Planos com Reembolso", "desc": "Amil 400 e Amil 750 oferecem opção de reembolso."},
            {"icon": "📱", "title": "Pelo App", "desc": "Solicite pelo app Amil em poucos cliques."},
            {"icon": "📋", "title": "Documentos", "desc": "Nota fiscal e relatório médico necessários."},
            {"icon": "⏰", "title": "Prazo Rápido", "desc": "Processamento em até 30 dias."},
            {"icon": "💰", "title": "Tabela de Valores", "desc": "Conforme tabela do plano contratado."},
            {"icon": "🏥", "title": "Livre Escolha", "desc": "Consulte qualquer médico e solicite reembolso."},
        ],
        "plans_title": "Planos Amil com Reembolso", "plans_subtitle": "Nem todos os planos oferecem.",
        "plans": [
            {"name": "Amil Fácil", "type": "SEM reembolso", "items": ["Plano econômico", "Somente rede", "Sem reembolso", "Menor mensalidade", "Ideal para rede"]},
            {"name": "Amil 400", "type": "COM reembolso", "featured": True, "items": ["Reembolso padrão", "Rede + livre escolha", "Nacional", "Tabela padrão", "Bom custo benefício"]},
            {"name": "Amil 750", "type": "Reembolso PREMIUM", "items": ["Maior reembolso", "Rede premium", "Livre escolha ampla", "Tabela elevada", "Plano mais completo"]},
        ],
        "network_title": "Como Solicitar", "network_subtitle": "Passo a passo do reembolso Amil.",
        "network": ["1. Consulte fora da rede", "2. Peça nota fiscal", "3. Relatório médico", "4. Abra o app Amil", "5. Envie documentos", "6. Acompanhe", "7. Receba reembolso"],
        "faqs": [
            {"q": "O Amil Fácil tem reembolso?", "a": "Não, somente Amil 400 e 750."},
            {"q": "Qual o prazo?", "a": "Até 30 dias úteis."},
            {"q": "Como solicitar pelo app?", "a": "No app Amil, vá em Reembolso e envie os documentos."},
        ],
    },
    {
        "slug": "plano-odonto-empresarial",
        "title": "Plano Odonto Empresarial | Preços 2026 | Virtua Corretora",
        "meta_description": "Plano odontológico empresarial 2026. Compare Bradesco Dental, Amil Dental, SulAmérica Odonto e mais. A partir de 2 vidas.",
        "h1": "Plano Odontológico<br>Empresarial",
        "operator_name": "planos odonto empresariais",
        "hero_subtitle": "Ofereça plano odontológico para sua empresa. Comparamos as melhores operadoras para encontrar a opção ideal a partir de 2 vidas, com preços especiais para empresas e MEI.",
        "hero_gradient": "linear-gradient(135deg, #0d4f8b 0%, #1a6fb5 50%, #2990d5 100%)",
        "hero_text_color": "#0d4f8b", "accent_color": "#1a6fb5",
        "badges": ["A partir de 2 vidas", "MEI Aceito", "Comparamos Operadoras", "Preços 2026"],
        "whatsapp_msg": "Olá, gostaria de cotação de plano odonto empresarial",
        "benefits_title": "Plano Odonto para Empresas",
        "benefits_subtitle": "Benefício odontológico para seus colaboradores com preços especiais.",
        "benefits": [
            {"icon": "💰", "title": "Preços PME", "desc": "Valores especiais para empresas, até 50%% menores que individual."},
            {"icon": "🦷", "title": "Cobertura Completa", "desc": "De prevenção a ortodontia e implantes conforme o plano."},
            {"icon": "🏢", "title": "A partir de 2 Vidas", "desc": "Contrate a partir de 2 colaboradores ou sócios."},
            {"icon": "📋", "title": "MEI Aceito", "desc": "Microempreendedores individuais podem contratar."},
            {"icon": "⭐", "title": "+10 Operadoras", "desc": "Comparamos Bradesco, Amil, SulAmérica, OdontoPrev e mais."},
            {"icon": "📱", "title": "Gestão Simples", "desc": "Inclusão e exclusão de vidas de forma simplificada."},
        ],
        "plans_title": "Operadoras de Odonto Empresarial", "plans_subtitle": "As melhores opções do mercado.",
        "plans": [
            {"name": "Bradesco Dental", "type": "Nacional · +26k dentistas", "items": ["Maior rede odonto do Brasil", "Planos desde o básico", "Ortodontia e implantes", "App Bradesco Dental", "Tradição Bradesco"]},
            {"name": "Amil Dental", "type": "Nacional · Premium", "featured": True, "items": ["Rede premium Amil", "Cobertura completa", "Ortodontia e implantes", "App Amil", "Suporte empresarial"]},
            {"name": "SulAmérica Odonto", "type": "Nacional · Qualidade", "items": ["Rede SulAmérica", "Profissionais qualificados", "Planos flexíveis", "App SulAmérica", "Gestão simplificada"]},
        ],
        "network_title": "Operadoras Parceiras", "network_subtitle": "Trabalhamos com as melhores.",
        "network": ["Bradesco Dental", "Amil Dental", "SulAmérica Odonto", "OdontoPrev", "MetLife Dental", "Porto Seguro Odonto", "Hapvida Dental", "Interodonto", "Odontosystem", "Uniodonto"],
        "faqs": [
            {"q": "Qual o plano odonto empresarial mais barato?", "a": "Depende da cobertura desejada. Fazemos a comparação gratuita entre operadoras."},
            {"q": "MEI pode contratar?", "a": "Sim! CNPJ ativo a partir de 2 vidas."},
            {"q": "Cobre ortodontia?", "a": "Sim, nos planos completos e premium de todas as operadoras."},
            {"q": "A Virtua cobra pela cotação?", "a": "Não! Cotação e consultoria são gratuitas."},
        ],
    },
]

if __name__ == "__main__":
    print(f"Generating {len(BATCH5)} pages (batch 5)...")
    for page in BATCH5:
        path = generate_page(page)
        print(f"  OK {path}")
    print(f"\nDone! {len(BATCH5)} pages created.")
